- name: "vars preference"
  hosts: frontend
  # vars: 
  #   full_name: "venkat reddy from play"
  #ars_files:
  # course.yaml
  # vars_prompt:
  # - name: full_name
  #   prompt: "Enter your full name"
  #   private: false
  tasks:
    - name: print vars perference
      vars:
       #full_name: "siva from task level"
      debug:
        msg: "Hello {{ full_name }}!"


# vars preference order
#1. command line arguments
#2. task level variables
#3. vars_files
#4. vars_prompt
#5. play variables
#6. inventory variables

