- name: check if a number is even or odd
  hosts: local
  connection: local
  vars:
    number: 7
  tasks:
    - name: check if the number is even or odd
      debug:
        msg: "the number {{number}} is even"
      when: number % 2 == 0
    - name: check if the number is even or odd
      debug:
        msg: "the number {{number}} is odd"
      when: number % 2 != 0