- name: install packages
  hosts: local
  connection: local
  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mysql
        - mongodb-mongosh