- name: demo on error handling
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check roboshop user exists or not
    command: id roboshop
    ignore_errors: yes # ignore errors: yes means that the task will continue even if the command fails
    register: user_output

  - name: print user output
    debug:
      msg: "{{ user_output }}"

  - name: create roboshop user
    command: useradd roboshop
    when: user_output.rc != 0 #rc is the return code of the command
          