- name: demo on error handling
  hosts: local
  connection: local
  tasks:
    - name: check roboshop user exists or not
      command: id roboshop
      ignore_errors: yes
      register: roboshop_user_output


    - name: print roboshop user output
      debug:
        msg: "{{ roboshop_user_output }}"