- name: demo on play level variable
  hosts: localhost
  connection: local # it will not ask for username and password
  vars:
    COURSE: "Ansible"
    TRAINER: "Venkey Reddy"
    DURATION: "2 months"
  tasks:
  - debug:
      msg: " i am learning {{ COURSE }} and i am loving it"
