- name: demo on prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: Enter your username:
      private: false

    - name: password
      prompt: Enter your password:
      private: true

  tasks:
    - name: print information
      debug:
        msg: " username is {{ username }} and password is {{ password }}"