[frontend]
172.31.21.14 COURSE="Ansible for node-1"
172.31.20.52 COURSE="Ansible for node-2"

[catalogue]
172.31.41.99    

[users]
172.31.41.100

[cart]
172.31.41.101

; group of groups
[roboshop:children]
frontend
catalogue
users
cart

[local]
localhost

; local group vars
[local:vars]
COURSE=ansible
TRAINER=REDDY
DURATION=2 weeks

[frontend:vars]
COURSE= "python"
TRAINER= "venkey bhai"
DURATION= "5 weeks"